version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_clothes_shop
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clothes_db
    ports:
      - "5455:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: docker.io/bitnami/redis:7.2
    container_name: redis_clothes_shop
    restart: always
    environment:
      - REDIS_PASSWORD= jfjakjjfajHJJj6362jhqdh!
    networks:
      - clothes-network
    ports:
      - "6459:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

networks:
  clothes-network:
    driver: bridge
